import React,{useState,useEffect,useRef} from 'react';
import {Blobatar} from '@blobatar/react';
import {happy,sleepy,thinking,idle} from 'blobatar/expression';
import {CATEGORIES,PRIORITIES,dateKey} from './model.js';

export function Icon({name,size=18,...props}) {
  const paths={plus:<path d="M12 5v14M5 12h14"/>,list:<path d="M8 6h12M8 12h12M8 18h12M3 6h.01M3 12h.01M3 18h.01"/>,matrix:<><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></>,edit:<path d="m15 4 5 5M4 20l5-1L20 8a3.5 3.5 0 0 0-5-5L4 14z"/>,trash:<path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7"/>,link:<path d="M10 13a5 5 0 0 0 7 .2l3-3a5 5 0 0 0-7-7l-2 2M14 11a5 5 0 0 0-7-.2l-3 3a5 5 0 0 0 7 7l2-2"/>,repeat:<path d="m17 2 4 4-4 4M21 6H7a4 4 0 0 0-4 4m4 12-4-4 4-4M3 18h14a4 4 0 0 0 4-4"/>,chevron:<path d="m9 5 7 7-7 7"/>,close:<path d="m6 6 12 12M6 18 18 6"/>};
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}>{paths[name]}</svg>;
}
export function dateLabel(date,today){if(!date)return 'No date';if(date===today)return 'Today';const next=new Date(today+'T12:00:00');next.setDate(next.getDate()+1);if(date===dateKey(next))return 'Tomorrow';return new Date(date+'T12:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short',...(date.slice(0,4)!==today.slice(0,4)?{year:'numeric'}:{})});}
function Character({task}) {
  const [celebrate,setCelebrate]=useState(false),previous=useRef(task.status);
  useEffect(()=>{const completed=previous.current!=='done'&&task.status==='done';previous.current=task.status;if(completed){setCelebrate(true);const timer=setTimeout(()=>setCelebrate(false),850);return()=>clearTimeout(timer);}setCelebrate(false);},[task.status]);
  const done=task.status==='done';
  return <div className={`task-character ${done?'resting':''} ${celebrate?'celebrating':''}`} aria-label={done?'Task companion resting':'Task companion active'} role="img"><Blobatar name={task.avatarSeed} size={64} animate={done?'hover':'always'} expression={celebrate?happy:done?sleepy:task.status==='progress'?thinking:idle} background="none" aria-hidden="true"/>{done&&<span className="sleep-mark" aria-hidden="true">z<span>z</span></span>}</div>;
}
export function TaskCard({task,onEdit,onComplete,onDelete,onPriority,today,compact=false}) {
  const priority=PRIORITIES[task.priority];
  return <article className={`task ${task.category} ${task.status==='done'?'done':''} ${compact?'compact':''}`} draggable={compact} onDragStart={e=>{e.dataTransfer.setData('text/daylist-id',task.id);e.dataTransfer.effectAllowed='move';}}>
    <Character task={task}/><div className="task-main"><div className="task-topline"><span className={`priority-label priority-${task.priority}`}>{priority.level} · {priority.name}</span>{task.repeat!=='none'&&<span className="repeat-label"><Icon name="repeat" size={12}/>{task.repeat==='daily'?'Daily':'Weekly'}</span>}</div><button className="task-title" onClick={()=>onEdit(task)} aria-label={`Edit ${task.title}`}>{task.title}</button>{task.notes&&<p className="task-note">{task.notes}</p>}<div className="task-meta"><span className="category-tag">{CATEGORIES[task.category]}</span>{task.date&&<span className={`due ${task.date<today&&task.status!=='done'?'overdue':''}`}>{task.date<today&&task.status!=='done'?'Overdue · ':''}{dateLabel(task.date,today)}</span>}{task.status==='progress'&&<span>In progress</span>}{task.url&&<a className="resource-link" href={task.url} target="_blank" rel="noopener noreferrer" aria-label={`Open resource for ${task.title}`}><Icon name="link" size={13}/>Resource</a>}</div><div className="task-bottom"><label className="priority-control"><span className="sr-only">Priority for {task.title}</span><select value={task.priority} onChange={e=>onPriority(task.id,e.target.value)}>{Object.entries(PRIORITIES).map(([key,p])=><option key={key} value={key}>{p.level} · {p.name}</option>)}</select></label><div className="task-actions"><button className="icon-button" onClick={()=>onEdit(task)} aria-label={`Edit task: ${task.title}`}><Icon name="edit" size={15}/></button><button className="icon-button" onClick={()=>onDelete(task)} aria-label={`Delete task: ${task.title}`}><Icon name="trash" size={15}/></button></div></div></div><input className="check" type="checkbox" checked={task.status==='done'} onChange={()=>onComplete(task.id)} aria-label={`${task.status==='done'?'Reopen':'Complete'} ${task.title}`}/>
  </article>;
}
export function Calendar({tasks,today,dateFilter,setDateFilter,month,setMonth}) {
  const offset=(month.getDay()+6)%7,last=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();
  return <section className="calendar-card" aria-label="Filter tasks by due date"><div className="calendar-heading"><h2>{month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><div><button className="icon-button" aria-label="Previous month" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><Icon name="chevron" className="rotate"/></button><button className="icon-button" aria-label="Next month" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><Icon name="chevron"/></button></div></div><div className="weekdays" aria-hidden="true">{'MTWTFSS'.split('').map((x,i)=><span key={i}>{x}</span>)}</div><div className="calendar-grid">{Array.from({length:offset},(_,i)=><span key={`empty${i}`}/>)}{Array.from({length:last},(_,i)=>{const date=new Date(month.getFullYear(),month.getMonth(),i+1),key=dateKey(date);return <button key={key} className={`${today===key?'today':''} ${dateFilter===key?'selected':''} ${tasks.some(t=>t.date===key)?'has-tasks':''}`} aria-current={today===key?'date':undefined} aria-pressed={dateFilter===key} aria-label={`Tasks due ${date.toLocaleDateString(undefined,{dateStyle:'full'})}`} onClick={()=>setDateFilter(dateFilter===key?null:key)}>{i+1}</button>;})}</div><div className="calendar-footer"><span><i/>Tasks scheduled</span><button className="text-button" onClick={()=>setDateFilter(null)}>{dateFilter?'Clear date':'All dates'}</button></div></section>;
}
