import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Blobatar} from '@blobatar/react';
import {idle} from 'blobatar/expression';
import 'blobatar/motion.css';
import './styles.css';
import {CATEGORIES,STATUSES,PRIORITIES,dateKey,normalizeTask,completeTask,sortTasks} from './model.js';
import {Icon,TaskCard,Calendar,dateLabel} from './components.jsx';
import TaskEditor from './TaskEditor.jsx';
import Matrix from './Matrix.jsx';
import {useTaskStore} from './useTaskStore.js';

function App(){
  const {tasks,tasksRef,commit,storageError}=useTaskStore();
  const [today,setToday]=useState(dateKey(new Date())),[month,setMonth]=useState(new Date(new Date().getFullYear(),new Date().getMonth(),1));
  const [view,setView]=useState('list'),[filter,setFilter]=useState('all'),[category,setCategory]=useState(null),[dateFilter,setDateFilter]=useState(null),[priorityFilter,setPriorityFilter]=useState(null),[editor,setEditor]=useState(null),[quick,setQuick]=useState(''),[toast,setToast]=useState(null);
  const toastTimer=useRef();
  useEffect(()=>{const refresh=()=>setToday(dateKey(new Date()));const tick=setInterval(refresh,60000);document.addEventListener('visibilitychange',refresh);return()=>{clearInterval(tick);clearTimeout(toastTimer.current);document.removeEventListener('visibilitychange',refresh);};},[]);
  function notify(text,undo=null){clearTimeout(toastTimer.current);setToast({text,undo});toastTimer.current=setTimeout(()=>setToast(null),undo?12000:4500);}
  function blank(priority=priorityFilter||'schedule'){const id=crypto.randomUUID();return {id,avatarSeed:id,title:'',date:dateFilter||'',dueTime:'',category:category||'work',priority,status:'todo',notes:'',url:'',repeat:'none',nextId:null,created:Date.now(),isNew:true};}
  function saveTask(draft){const {isNew,...task}=draft;try{normalizeTask(task);}catch{return 'Check the task details before saving.';}const existing=tasks.find(t=>t.id===task.id);let next=existing?tasks.map(t=>t.id===task.id?task:t):[...tasks,task];if(task.status==='done'&&existing?.status!=='done'){next=next.map(t=>t.id===task.id?{...t,status:'todo'}:t);next=completeTask(next,task.id,today);}if(commit(next)){setEditor(null);reset();notify(existing?'Task updated.':'Task created.');return '';}return 'Could not save. Your input is still here.';}
  function toggle(id){const task=tasks.find(t=>t.id===id);if(!task)return;const next=completeTask(tasks,id,today);if(commit(next))notify(task.status==='done'?'Task reopened.':next.length>tasks.length?'Completed. Next occurrence scheduled.':'Task completed.');}
  function remove(task){if(commit(tasks.filter(t=>t.id!==task.id)))notify('Task deleted.',()=>{const current=tasksRef.current;if(commit([...current.filter(t=>t.id!==task.id),task]))notify('Task restored.');});}
  function changePriority(id,priority){if(Object.hasOwn(PRIORITIES,priority)&&commit(tasks.map(t=>t.id===id?{...t,priority}:t)))notify(`Priority changed to ${PRIORITIES[priority].level}.`);}
  function reset(){setFilter('all');setCategory(null);setDateFilter(null);setPriorityFilter(null);}
  const shown=sortTasks(tasks.filter(t=>(filter==='all'||t.status===filter)&&(!category||t.category===category)&&(!dateFilter||t.date===dateFilter)&&(!priorityFilter||t.priority===priorityFilter)));
  const done=tasks.filter(t=>t.status==='done').length,percent=tasks.length?Math.round(done/tasks.length*100):0,hour=new Date().getHours();
  const start=new Date(today+'T12:00:00');start.setDate(start.getDate()-((start.getDay()+6)%7));const week=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return d;});
  const card=t=><TaskCard key={t.id} task={t} onEdit={setEditor} onComplete={toggle} onDelete={remove} onPriority={changePriority} today={today} compact={view==='matrix'}/>;
  return <div className="app"><header className="topbar"><a className="brand" href="./" aria-label="Grove home"><span className="brand-mark" aria-hidden="true"><svg viewBox="0 0 28 28" fill="none"><path d="M14 24V11" stroke="currentColor" strokeWidth="2.3" strokeLinecap="round"/><path d="M14 15C9 15 5.8 12.5 5.8 7.5c5.3-.2 8.2 2.4 8.2 7.5Z" fill="currentColor" opacity=".75"/><path d="M14 11C14.4 6.2 17.3 3.2 22.2 3c.4 5.2-2.4 8.2-8.2 8Z" fill="currentColor"/></svg></span><span>grove</span></a><nav className="view-switch" aria-label="Task view"><button aria-pressed={view==='list'} onClick={()=>setView('list')}><Icon name="list"/>Plan</button><button aria-pressed={view==='matrix'} onClick={()=>setView('matrix')}><Icon name="matrix"/>Matrix</button></nav><button className="primary" onClick={()=>setEditor(blank())}><Icon name="plus"/>New task</button></header><main>
    <header className="page-header"><div><p className="date-label">{new Date(today+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</p><h1>{hour<12?'Good morning':hour<18?'Good afternoon':'Good evening'}</h1></div><button className="workspace-label" onClick={reset}>My tasks <span>{tasks.length}</span></button></header>
    <section className="overview" aria-label="Task summary"><div className="completion"><div className="completion-ring" style={{'--progress':`${percent}%`}}><div><strong>{percent}%</strong><span>complete</span></div></div><div className="completion-copy"><h2>Your progress</h2><p>{done} of {tasks.length} {tasks.length===1?'task':'tasks'} complete</p><div className="progress-track"><div style={{width:`${percent}%`}}/></div></div></div><div className="stats">{Object.entries(STATUSES).map(([key,name])=><button key={key} onClick={()=>setFilter(key)}><span className="stat-number">{tasks.filter(t=>t.status===key).length}</span><span>{name}</span></button>)}</div></section>
    <div className={`workspace ${view==='matrix'?'matrix-workspace':''}`}><section className="tasks-pane" aria-label="Your task list"><div className="list-header"><div><p className="eyebrow">{view==='matrix'?'PRIORITY MAP':'YOUR SCHEDULE'}</p><h2>{view==='matrix'?'The Eisenhower matrix':dateFilter?dateLabel(dateFilter,today):'All tasks'} <span className="list-count">{shown.length}</span></h2></div>{(filter!=='all'||category||dateFilter||priorityFilter)&&<button className="text-button" onClick={reset}>Clear filters</button>}</div>
    {view==='list'&&<div className="week-strip" aria-label="This week">{week.map(d=>{const key=dateKey(d);return <button key={key} className={`week-day ${key===today?'today':''} ${tasks.some(t=>t.date===key)?'has-tasks':''}`} aria-pressed={dateFilter===key} aria-label={`Show tasks for ${d.toLocaleDateString(undefined,{dateStyle:'full'})}`} onClick={()=>{setDateFilter(dateFilter===key?null:key);setMonth(new Date(d.getFullYear(),d.getMonth(),1));}}><span>{d.toLocaleDateString(undefined,{weekday:'short'})}</span><strong>{d.getDate()}</strong></button>;})}</div>}
    <div className="task-toolbar"><div className="filters" aria-label="Filter by status">{[['all','All'],...Object.entries(STATUSES)].map(([key,name])=><button key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{name}</button>)}</div><select className="priority-filter" aria-label="Filter by priority" value={priorityFilter||''} onChange={e=>setPriorityFilter(e.target.value||null)}><option value="">All priorities</option>{Object.entries(PRIORITIES).map(([key,p])=><option key={key} value={key}>{p.level} · {p.name}</option>)}</select></div>
    {view==='list'?<><form className="quick-form" onSubmit={e=>{e.preventDefault();if(!quick.trim())return;const {isNew,...task}=blank();task.title=quick.trim();task.status=filter==='progress'?'progress':'todo';if(commit([...tasks,task])){setQuick('');if(filter==='done')setFilter('todo');notify('Task added.');}}}><Icon name="plus"/><input aria-label="Quick task name" value={quick} onChange={e=>setQuick(e.target.value)} placeholder="Add a task…" required maxLength={200}/><button type="submit" aria-label="Add quick task">Add <span aria-hidden="true">↵</span></button></form>{shown.map(card)}{!shown.length&&<div className="empty"><Blobatar name="daylist-new-start" size={90} animate="always" expression={idle} aria-hidden="true"/><h3>{tasks.length?'No matching tasks':'Your list starts here'}</h3><p>{tasks.length?'Change the filters or add a task to this view.':'Give your first task a name and a priority.'}</p><button className="text-button" onClick={()=>setEditor(blank())}>Add task with details</button></div>}</>:<Matrix shown={shown} tasks={tasks} renderCard={card} onPriority={changePriority} onAdd={p=>setEditor(blank(p))}/>}
    </section>{view==='list'&&<aside className="right-pane"><section className="priority-snapshot"><div className="section-heading"><h2>Priorities</h2><button className="text-button" onClick={()=>setView('matrix')}>Open matrix</button></div><div className="mini-matrix">{Object.entries(PRIORITIES).map(([key,p])=><button key={key} className={`mini-${key}`} aria-pressed={priorityFilter===key} onClick={()=>setPriorityFilter(priorityFilter===key?null:key)}><span>{p.name}</span><strong>{tasks.filter(t=>t.priority===key&&t.status!=='done').length}</strong></button>)}</div></section><Calendar tasks={tasks} today={today} dateFilter={dateFilter} setDateFilter={setDateFilter} month={month} setMonth={setMonth}/><section className="categories-card"><div className="section-heading"><h2>Categories</h2><span>3</span></div><div id="categories">{Object.entries(CATEGORIES).map(([key,name])=><button key={key} className={`category-filter ${key}`} aria-pressed={category===key} onClick={()=>setCategory(category===key?null:key)}><span><span className="color-square"/>{name}</span><span>{tasks.filter(t=>t.category===key).length}</span></button>)}</div></section></aside>}</div>
    {storageError&&<p className="storage-error" role="alert">{storageError}</p>}<footer className="app-footer"><a href="https://blobatar.dev/" target="_blank" rel="noopener noreferrer">Characters by Blobatar</a></footer>
    </main>{editor&&<TaskEditor key={editor.id} task={editor} onClose={()=>setEditor(null)} onSave={saveTask}/>}<div className="toast" role="status" hidden={!toast}><span>{toast?.text}</span>{toast?.undo&&<button onClick={toast.undo}>Undo</button>}</div></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
