import React,{useState,useEffect,useRef} from 'react';
import {Blobatar} from '@blobatar/react';
import {sleepy,idle} from 'blobatar/expression';
import {CATEGORIES,STATUSES,PRIORITIES,validLink,dateKey} from './model.js';
import {Icon} from './components.jsx';

export default function TaskEditor({task,onClose,onSave}) {
  const dialog=useRef(null),[draft,setDraft]=useState(task),[error,setError]=useState(''),[quickDue,setQuickDue]=useState('');
  useEffect(()=>{const opener=document.activeElement;dialog.current.showModal();dialog.current.querySelector("#title").focus();return()=>{if(opener instanceof HTMLElement&&opener.isConnected)opener.focus();};},[]);
  const update=(key,value)=>setDraft(d=>({...d,[key]:value}));
  function submit(e){e.preventDefault();const due=e.currentTarget.querySelector('#date').value,time=e.currentTarget.querySelector('#time').value;if(!draft.title.trim()){setError('Enter a task name.');return;}if(!validLink(draft.url.trim())){setError('Use a complete http:// or https:// resource link.');return;}if(draft.repeat!=='none'&&!due){setError('Choose a due date for a repeating task.');return;}const message=onSave({...draft,date:due,dueTime:time,title:draft.title.trim(),url:draft.url.trim()});if(message)setError(message);}
  function previewMoss(){const d=new Date();d.setDate(d.getDate()-1);update('date',dateKey(d));update('dueTime','09:00');setError('Preview date set. Save to grow the moss.');}
  function setDueIn(minutes){const d=new Date(Date.now()+minutes*60000);update('date',dateKey(d));update('dueTime',`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`);setQuickDue(String(minutes));setError(`Due in ${minutes<60?`${minutes} minutes`:`${minutes/60} hour${minutes===60?'':'s'}`}.`);}
  return <dialog ref={dialog} onCancel={e=>{e.preventDefault();onClose();}} aria-labelledby="editor-heading"><form onSubmit={submit} className="editor-form"><div className="dialog-header"><p className="eyebrow">TASK DETAILS</p><button type="button" className="icon-button" onClick={onClose} aria-label="Close task editor"><Icon name="close"/></button></div><div className="editor-heading"><Blobatar name={draft.avatarSeed} size={52} animate="always" expression={draft.status==='done'?sleepy:idle} aria-hidden="true"/><h2 id="editor-heading">{task.isNew?'New task':'Edit task'}</h2></div><label htmlFor="title">Task name</label><input autoFocus id="title" value={draft.title} maxLength={200} required onChange={e=>update('title',e.target.value)} placeholder="What needs doing?"/>
    <div className="form-row"><div><label htmlFor="priority">Priority</label><select id="priority" value={draft.priority} onChange={e=>update('priority',e.target.value)}>{Object.entries(PRIORITIES).map(([key,p])=><option value={key} key={key}>{p.level} · {p.name}</option>)}</select><p className="field-hint">{PRIORITIES[draft.priority].description}</p></div><div><label htmlFor="status">Status</label><select id="status" value={draft.status} onChange={e=>update('status',e.target.value)}>{Object.entries(STATUSES).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></div></div>
    <div className="form-row"><div><label htmlFor="date">Due date {draft.repeat==='none'&&<span>(optional)</span>}</label><input id="date" type="date" value={draft.date} required={draft.repeat!=='none'} onInput={e=>update('date',e.currentTarget.value)} onChange={e=>update('date',e.target.value)}/></div><div><label htmlFor="time">Due time <span>(optional)</span></label><input id="time" type="time" value={draft.dueTime||''} onInput={e=>update('dueTime',e.target.value)} onChange={e=>update('dueTime',e.target.value)}/></div></div><button type="button" className="preview-moss" onClick={previewMoss}>Set yesterday to preview moss growth</button><div className="form-row"><div><label htmlFor="repeat">Repeat</label><select id="repeat" value={draft.repeat} onChange={e=>update('repeat',e.target.value)}><option value="none">Does not repeat</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select></div></div>{draft.repeat!=='none'&&<p className="repeat-help">Completing this task creates the next occurrence. Reopening it keeps the next occurrence.</p>}
    <label htmlFor="quickDue">Quick due</label><select id="quickDue" value={quickDue} onChange={e=>e.target.value&&setDueIn(Number(e.target.value))}><option value="">Choose a countdown…</option><option value="5">In 5 minutes</option><option value="15">In 15 minutes</option><option value="30">In 30 minutes</option><option value="60">In 1 hour</option></select><button type="button" className="preview-moss" onClick={previewMoss}>Set yesterday to preview moss growth</button>
    <fieldset><legend>Category</legend><div className="category-options">{Object.entries(CATEGORIES).map(([key,name])=><label className={key} key={key}><input type="radio" name="category" value={key} checked={draft.category===key} onChange={()=>update('category',key)}/>{name}</label>)}</div></fieldset>
    <label htmlFor="notes">Notes <span>(optional)</span></label><textarea id="notes" rows={3} value={draft.notes} maxLength={4000} onChange={e=>update('notes',e.target.value)} placeholder="Details to keep with this task"/>
    <label htmlFor="url">Resource link <span>(optional)</span></label><input id="url" type="url" value={draft.url} maxLength={2048} onChange={e=>update('url',e.target.value)} placeholder="https://…"/>
    {error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" type="submit">{task.isNew?'Create task':'Save changes'}</button></div>
  </form></dialog>;
}
